  #################   DATASET CONFIG   ###################

  project_name: "sroie19"    # also the folder name of the dataset that under ./data folder
  train_imgs: images/train
  val_imgs: images/val
  train_anns: annotations/train.json
  val_anns: annotations/val.json
  #################   TRAINING CONFIG   ###################
  
  pretrained: "./weights/PAN_resnet18_FPEM_FFM.pth"

  gpu_devices: '0'                     # supports multi-gpus
  num_epochs: 100
  batch_size: 8
  num_workers: 2
  
  image_size: 640

  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "step_lr"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
    step_size: 35
    gamma: 0.1                                   # if need to specify more scheduler arguments, do it here

  model:
    backbone: "resnet18"
    fpem_repeat: 2
    pretrained: True
    segmentation_head: "FPEM_FFM"

  loss: 
    alpha: 0.5
    beta: 0.25
    delta_agg: 0.5
    delta_dis: 3
    ohem_ratio: 3
